# ?? ?? ?? (???? 8080)
server:
  port: 8080

# --- ?????? ? JPA ?? ---
spring:
  # ??? ?? ?? (MySQL ?? ??)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1013

  # JPA (Java Persistence API) ??
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        # ???? SQL ??? ?? ?? ???
        format_sql: true
        # SQL ??? ???? ???? ?? ??? ??
        show_sql_parameters: true

    # ??? ???? SQL ??? ??
    show-sql: true

# ?? ?? ?? (JPA? ???? SQL? ? ??? ?? ??)
logging:
  level:
    #    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace  # ??? ?? ?? ?? ?????? ??? ? ??? ?????.