# 워크플로우의 이름
name: Deploy Spring Boot App to AWS ECR

# main 브랜치에 push 이벤트가 발생했을 때 이 워크플로우를 실행
on:
  push:
    branches:
      - main

# 환경 변수 설정
env:
  AWS_REGION: ap-northeast-2     # 사용할 AWS 리전 (서울)
  ECR_REPOSITORY: boardprojct    # ECR 리포지토리 이름

jobs:
  build-and-push-to-ecr:
    runs-on: ubuntu-latest

    # OIDC 토큰을 사용하기 위한 권한 설정
    permissions:
      id-token: write
      contents: read

    steps:
      # 1. 소스 코드 체크아웃
      - name: Checkout
        uses: actions/checkout@v3

      # 2. AWS 자격 증명 설정 (OIDC 역할 사용)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      # 3. Amazon ECR에 로그인
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # 4. Docker 이미지 빌드 및 ECR로 푸시
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }} # 커밋 해시를 이미지 태그로 사용
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG